name: network
description: Dart package which manages network layer
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  very_good_analysis: ^3.0.1
